name: Unit Test Job

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Unit Tests and Coverage
        run: go test ./... -coverprofile=coverage && go tool cover -func=coverage